### ISSUE TITLE
Hash table collision resolution

### ISSUE THREAD

**Issue by Kureev** [thejameskyle/itsy-bitsy-data-structures#19]
Hey @thejameskyle,

What about collision resolutions? I can make a PR with list resolution and/or open addressing, if you like the idea.

**Comment by vitkarpov** [comment]
It's gonna turn into "complete guide into essential data structures" soon :)

**Comment by thejameskyle** [comment]
I don't think going through that adds that much value. Especially when it can't be addressed without going through the topics covered later on in other data structures.

These are not meant to be realistic implementations of data structures, they are meant to be abstract implementations that serve to ground the ideas that are being explained in the comments.
