### ISSUE TITLE
Specify runtime difference between sorted/unsorted arrays

### ISSUE THREAD

**Issue by Aweary** [thejameskyle/itsy-bitsy-data-structures#20]
On mobile so I can't get s PR going, but the table comparing basic DS runtimes for access/search/insert/delete should have a row for Array (sorted) and Array (unsorted), since they differ a lot.

For example, searching in a sorted array can be `O(lg n)` and insertion in an unsorted array is `O(1)`

**Comment by thejameskyle** [comment]
I feel like that will only confuse the lesson to be learned here about them. I could add all sorts of details like this but I don't feel that these sort of details will add a lot of value to beginners. This isn't a good resource for a reference guide on individual data structures.

**Comment by Aweary** [comment]
The issue is that it's innacurate either way right now. Are you assuming a sorted array? If so, search is not `O(n)` it's `O(log n)`. Is it unsorted? Then insertion is not `O(n)` it's `O(1)`.

I get that it's a slippery slope adding detail after detail, but right now this is misleading IMO and should be clarified

**Comment by L-u-k-e** [comment]
I think that the section on lists reads intuitively as being unsorted, making the `O(n)` search comment accurate in that context. 

In that vein, when the author talks about inserting and deleting, any context regarding the sorted nature of the list is unnecessary IMO. What **is** necessary is context regarding whether or not you care **where** you insert the item. The author shows that if you want to insert/delete an item in a specific spot (in his example, the beginning with the `shift`/`unshift` ops) that is `O(n)`. 

So, disregarding whether the list is sorted or not, the worst case for inserting/ deleting is still `O(n)`, where the worst case is "I care where I insert/ delete and I want to do so st the beginning"

**Comment by Aweary** [comment]
If you're inserting into a specific index then there's some conception of order meaning by definition that it's a sorted array. Using `shift` and `unshift` is just a poor implementation detail in this case when it comes to inserting into an unsorted array (appending to the end of the array should be `O(1)`)

**Comment by Aweary** [comment]
To clarify, using `shift` and `unshift` should usually be avoided if you're looking to implement a stack or something. Just because you *can* use them and get `O(n)` inserts doesn't mean you should and doesn't mean that it's a tight bound on the possible runtime of these operations.

You can always use `push` and iterate backwards to implement the same behavior with `O(1)` inserts

**Comment by L-u-k-e** [comment]
I agree that you shouldn't be using `shift`/`unshift` if you're implementing a queue (and the author mentions this as well). The point still stands however, that they _do exist_ as operations that do insertion/deletion with `O(n)` time complexity. These operations exist independently of the ordering of any given list. 

Your point seems to be as follows:

- In practical use cases you won't be using any operations that do insertion/deletion beyond the last element in the list (`O(1)`) unless the list is ordered, but if you do need to do such an operation, you probably shouldn't be using a list.

My comment was not addressing the point made in the previous paragraph, but rather your specific comment:

> The issue is that it's inaccurate either way right now. Are you assuming a sorted array? If so, search is not O(n) it's O(log n). Is it unsorted? Then insertion is not O(n) it's O(1).


I'm stating that **within the context of this specific work** your statement does not hold true. I believe the authors original statement of `O(n)` makes more sense in the context in which it lives.

I am **not** stating that your statement isn't true real-world use cases that would certainly be relevant in a variety of other contexts. I do think that this is an important point to make, but this is supposed to be an introduction to data structures, not algorithms.

Perhaps the best solution would be to add a sentence under the section you originally called out stating that those time complexities can be mitigated depending on how you use the data structure.

**Comment by Aweary** [comment]
No, my point is that the table lists the running time of an Array, without qualification, inaccurately. It is not describing a list, or some specific implementation that uses an array, it's talking about the data structure itself. I'm not talking about practical or real world implementations; I'm talking about theoretical worst-case running time for the data structure.

Obviously you *can* have  an `O(n)` insertion implementation with sorted or unsorted arrays, but you can also have `O(n^2)` or `O(!n)` if you wanted to, right? There's nothing stopping you from being super inefficient, but that doesn't bring any value. If you're discussing the pros and cons of a DS then you need to discuss it in terms of its omptimal worst-case runtimes.

The issue is that a sorted array and unsorted array are two fundamentally different structures that have different time complexities when it comes to searching, insertion, and deletion.

>I'm stating that within the context of this specific work your statement does not hold true. I believe the authors original statement of O(n) makes more sense in the context in which it lives

The context of this repo is an introduction to data structures. I don't think @jameskyle is trying to discuss only the running time of his specific implementations here, as that's not really useful as an intro to data structures. Plus, what I'm saying applies to *all arrays regardless of implementation* as its an aspect of the data structure's running time, not implementation.

>I am not stating that your statement isn't true in real-world use cases that would certainly be relevant in a variety of other contexts. I do think that this is an important point to make, but this is supposed to be an introduction to data structures, not algorithms.

you literally can't discuss data structures meaningfully without algorithms. Any action you peform with a DS requires some form of algorithm. Big O notation describes running times for algorithms, not data structures.

**Comment by Aweary** [comment]
Back to the original issue @jameskyle, I know this isn't a deep dive into any specific structure, but you can't make accurate claims about the running time of operations on an array without stating if it's sorted or not. I think it's important for beginners to know that, as its pretty fundamental.

**Comment by Aweary** [comment]
And to be clear, I'm talking about [this table specifically](https://github.com/thejameskyle/itsy-bitsy-data-structures/blob/master/itsy-bitsy-data-structures.js#L237) and nothing else.

**Comment by thejameskyle** [comment]
That table was based on the one seen on http://bigocheatsheet.com/, and when we're talking about average performance it is correct. 

The normalized algorithm for insertion in an array given a position and assuming nothing about the array is:

```js
insert(array, position, value):
  previous = value
  
  while position < length(array):  // << O(n)
    current = get(array, position)
    set(array, position, previous)
    previous = current
    position = position + 1
  
  set(array, length(array), previous)
```

Deletion is basically the same just moving items backwards `O(n)`. Searching (assuming nothing about the array) is also `O(n)`.

What is written is correct. The only thing that would change by distinguishing sorted and unsorted is searching and I don't believe that's worth potentially confusing a reader at that stage.
  
I'm going to close this as I want to keep what is written

**Comment by Aweary** [comment]
Cool, I totally understand where you're coming from!

> The only thing that would change by distinguishing sorted and unsorted is searching

Not true. If you did make the distinction then for unsorted arrays insertion would be `0(1)` and deletion would be `O(1)` as well if you already had the index/pointer to the item. It wouldn't make sense to make the distinction and then fall back to a normalized algorithm for evaluating insert/delete. 

But yeah, I get that this might too granular for what you're wanting to explain here 👍

**Comment by thejameskyle** [comment]
> If you did make the distinction then for unsorted arrays insertion would be

Unsorted arrays assuming you want to push to the end. If you have to insert anywhere else you have to follow the same algorithm, unless the array is backed by another data structure in which case its not really an array

**Comment by Aweary** [comment]
That's the thing though, if the array is unsorted then by definition the order has no meaning. if you have to insert at some specific index, then your array has some sense of order and is not unsorted. If your array is unsorted it doesn't matter where you insert at, which is why you can in all cases append to the end and get `O(1)`

**Comment by thejameskyle** [comment]
Practice vs. theory: the world's greatest bike-shedder

**Comment by Aweary** [comment]
But what's the average worst case running time of our bike-shedding?

**Comment by thejameskyle** [comment]
O(MG!)

Where M is the mass of of the bike-shed, and G is the good we could be doing if we weren't busy bike-shedding.
