### ISSUE TITLE
wrong order in list push method

### ISSUE THREAD

**Issue by parkgrrr** [thejameskyle/itsy-bitsy-data-structures#34]
In the push method for the list, shouldn't you increase the length of the list before you populate the last item?  It currently reads like this.
`push(value) {
    this.memory[this.length] = value;
    this.length++;
  }`

Shouldn't it be like this?

`push(value) {
    this.length++;
    this.memory[this.length] = value;
  }`

**Comment by NuclearCoder** [comment]
no because `memory[length]` actually is the `length+1`-th item, so it's actually correct

**Comment by thejameskyle** [comment]
yup ^

**Comment by parkgrrr** [comment]
Thanks for the help guys!
