### ISSUE TITLE
Can I use it to make a video about data structures?

### ISSUE THREAD

**Issue by NuclearCoder** [thejameskyle/itsy-bitsy-data-structures#35]
It would be more detailed but you definitely explain very well!
And of course I would give you credit.

**Comment by jonathanmeguira** [comment]
Sure thing

Jonathan Meguira

**Comment by NuclearCoder** [comment]
Thank you :)

**Comment by Cronixx** [comment]
You could inform us when you are finished, i would be glad to see it!

2016-09-16 14:17 GMT+02:00 NuclearCoder <notifications@github.com>:

**Comment by NuclearCoder** [comment]
I intend to make it a series instead of a single video. The series would be about algorithmics in general.

**Comment by thejameskyle** [comment]
@jonathanmeguira @Cronixx Who the hell are you people? Neither of you are involved in this project

@NuclearCoder the project is licensed with creative commons v4: https://github.com/thejameskyle/itsy-bitsy-data-structures/blob/master/LICENSE so feel free to use it however you please

**Comment by thejameskyle** [comment]
@NuclearCoder In the future, I would check that the people responding to you are actually contributors to the project and not a couple of randos doing whatever that was

**Comment by NuclearCoder** [comment]
Whoops, no it's my bad I thought I mistook @jonathanmeguira with you @thejameskyle

**Comment by jonathanmeguira** [comment]
my bad I when i saw @NuclearCoder message I thought he was referring to some other github of mine, sorry for the misunderstanding all credit goes to theJamesKyle
