### ISSUE TITLE
Memory blocks can't be resized in real life

### ISSUE THREAD

**Issue by poxu** [thejameskyle/itsy-bitsy-data-structures#40]
First of all, javascript arrays are not just blocks of memory, but you probably know that, since you store length independently,  even though array has length property, because in real life memory doesn't have a length.

I'd like to remind you, that in real life you also can't just grow a block of memory.
You have to first allocate another block of memory, bigger than the first one and then copy elements from the old block to the new block one by one.
That operation takes O(N) to perform.

The idea of having a list backed by an internal array has two drawbacks.
First one is that you have to copy elements, when you remove or insert, and the second one is that you have to allocate new memory and copy elements when your internal array is too small, and you didn't say anything about that second issue.

If you really want to explain how to work with arrays, which are just blocks of memory, you have to explain resizing.

**Comment by thejameskyle** [comment]
I don't need to explain every detail. HashTables are not realistic either because we just skip over the collisions issue. The point is not to explain the actual implementations for each of these but to introduce different topics sequentially in order to give people a solid intro.
