### ISSUE TITLE
Error when removing inexistent head

### ISSUE THREAD

**Issue by rcsole** [thejameskyle/itsy-bitsy-data-structures#41]
Hi @thejameskyle! First off great repo, thanks for creating it.

Similarly to #25, I know this is generic but if you remove the head
and the head is already `null`, I think it would throw an error
complaining how `Cannot read property 'next' of null`, instead
we could be more specific and throw a more helpful error. Maybe
it's not in the scope of this though.

```js
remove(position) {
  // Throw an error, instead of calling head.null, where head = null
  if (!head) {
    throw new Error('Removing from empty list')
  }
  /* ... */
```

Another option could be to `return` early. What do you think?
I can open a PR if you want.

**Comment by thejameskyle** [comment]
a throw would be good
