### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by zhang-yuan** [thejameskyle/itsy-bitsy-data-structures#43]
comments of `QUEUES`  in `itsy-bitsy-data-structures.js`

> [Next, we're going to build a queue which is **complimentary** to stacks.](https://github.com/thejameskyle/itsy-bitsy-data-structures/blob/master/itsy-bitsy-data-structures.js#L746)

may be `complementary` ?

**Comment by Steakeye** [comment]
Well, I think Queues might rather like Stacks ;)

**Comment by zhang-yuan** [comment]
😂 OK, I see. Thanks for the response!

**Comment by thejameskyle** [comment]
heh, I think @Steakeye was just joking. You are right it should be complementary

**Comment by thejameskyle** [comment]
fixed

**Comment by Steakeye** [comment]
Yep, I was kidding :) Glad it's fixed!
